# Generated by Django 4.1.1 on 2022-09-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
